#!/bin/bash
####################################
#ssr://server:port:protocol:method:obfs:password_base64/?params_base64
#	params_base64: obfsparam=obfsparam_base64&protoparam=protoparam_base64&remarks=remarks_base64&group=group_base64
#
#CMD:
#	ssr-local -l $LISTEN -s $IP -p $PORT -k $PASSWD -m $METHOD
####################################
PARAM_LIST="ip port protocol method obfs password obfsparam protoparam remarks group"
CHECK_LIST="ip port protocol method password "
LISTEN=${LISTEN:-20000}

#value_get base64_string index
value_get(){
	echo "$1" | sed 's/[:\/\?]/ /g' | awk "{print \$$2}"
}

ip_get(){ 
	local value
	value=`value_get "$1" 1`
	[ -z "$value" ] && return 1
	echo "-s $value"
}
port_get(){
	local value
	value=`value_get "$1" 2`
	[ -z "$value" ] && return 1
	echo "-p $value"
}
protocol_get(){
	local value
	value=`value_get "$1" 3`
	[ -z "$value" ] && return 0
	echo "-O $value"
}
method_get(){
	local value
	value=`value_get "$1" 4`
	[ -z "$value" ] && return 1
	echo "-m $value"
}
obfs_get(){
	local value
	value=`value_get "$1" 5`
	[ -z "$value" ] && return 0
	echo "-o $value"
}
password_get(){
	local value
	value=`value_get "$1" 6`
	[ -z "$value" ] && return 1
	value=`base64_decode "$value"`
	echo "-k $value"
}

param_get(){
	local params
	params=`value_get $1 7`
	[ -z "$params" ] && return 0
	params=`echo "$params" | sed "s/.*$2=//;s/&.*//"`
	[ -z "$params" ] && return 0
	base64_decode "$params"
	return 0
}
obfsparam_get(){
	local value
	value=`param_get "$1" obfsparam`
	[ -z "$value" ] && return 0
	echo "-g $value"
}
protoparam_get(){
	local value
	value=`param_get "$1" protoparam`
	[ -z "$value" ] && return 0
	echo "-G $value"
}
remarks_get(){
	return 0
}
group_get(){
	return 0
}

#################################
#Public functions
#resource_decode resource
resource_decode(){
	local params
	local value
	DECODE=`base64_decode $1` || {
	      #decode fail
		DECODE=""
		return 1
	}
	value=`echo "$DECODE" | sed 's/.*\/?//'`
	params=`base64_decode "$value"`
	[ $? != 0 ] && return 0
	value=`echo "$DECODE" | sed 's/\/?.*//'`
	DECODE="${value}/?${params}"
	return 0
}

#resource_parse resource
resource_parse(){
	local name
	local value
	#set +H
	[ -z "$DECODE" ] && return 1
	for name in $PARAM_LIST;do
		value=`${name}_get "$DECODE"`
		eval $name=\"$value\"
		#echo "$name=$value"
		#echo "$name=$(eval echo \$$name)"
	done
	return 0
}
# config_generate port config_file
config_generate(){
	lport="-l $1"
	return 0
}
# command_start config_file
command_start(){
	echo "ssr-local $lport $ip $port $method $password $obfs $obfsparam $protocol $protoparam"
	ssr-local $lport $ip $port $method $password $obfs $obfsparam $protocol $protoparam >/dev/null 2>&1 &
	return $!
}
# command_stop pid
command_stop(){
	kill $1
}

# command_run config_file
command_run(){
	nohup ssr-local $lport $ip $port $method $password $obfs $obfsparam $protocol $protoparam >/dev/null 2>&1 &
	echo "ssr-local $lport $ip $port $method $password $obfs $obfsparam $protocol $protoparam >/dev/null 2>&1"
}
