#!/bin/bash
####################################
#ss://method:password@server:port
#
#eg:
#       aes-256-gcm:CUndSZnYsPKcu6Kj8THVMBHD@103.156.50.107:39772
#
#CMD:
#	ss-local -l $LISTEN -s $IP -p $PORT -k $PASSWD -m $METHOD
####################################
PARAM_LIST="ip port passwd method"
LISTEN=${LISTEN:-20000}

#value_get base64_string index
value_get(){
	echo -n $1 | sed 's/#.*//;s/ *$//' | base64 -d 2>/dev/null | sed 's/[:@]/ /g' | awk "{print \$$2}"
}

ip_get(){ 
	local value
	value=`value_get "$1" 3`
	[ -z "$value" ] && return 1
	echo "-s $value"
}
port_get(){
	local value
	value=`value_get "$1" 4`
	[ -z "$value" ] && return 1
	echo "-p $value"
}
passwd_get(){
	local value
	value=`value_get "$1" 2`
	[ -z "$value" ] && return 1
	echo "-k $value"
}
method_get(){
	local value
	value=`value_get "$1" 1`
	[ -z "$value" ] && return 1
	echo "-m $value"
}

#EXECUTE='ss-local -l "$LISTEN" $ip $port $passwd $method'
EXECUTE='ss-local -l $LISTEN $ip $port $passwd $method'
