#!/bin/bash
####################################
#ss://method:password@server:port
#eg:
#       aes-256-gcm:CUndSZnYsPKcu6Kj8THVMBHD@103.156.50.107:39772
#EncodeType1:
#	(method:password | base64)+@server:port
#EncodeType2:
#	full_string | base64
#CMD:
#	ss-local -l $LISTEN -s $IP -p $PORT -k $PASSWD -m $METHOD
####################################
PARAM_LIST="ip port passwd method"
LISTEN=${LISTEN:-20000}

decode_type1(){
	local prefix
	local suffix
	local result
	prefix=`echo -n $1 | sed 's/@.*//'`
	suffix=`echo -n $1 | sed 's/.*@//'`
	[ -z "$prefix" -o -z "$suffix" ] && return 1
	result=`base64_decode "$prefix"`
	[ $? != 0 ] && return 1
	#Find ":" in result
	prefix=`echo "$result" | sed 's/.*:.*//'`
	[ -n "$prefix" ] && return 1
	echo "${result}@${suffix}"
}
decode_type2(){
	base64_decode "$1"
}

#value_get base64_string index
value_get(){
	local value
	value=`echo -n $1 | sed 's/#.*//;s/ *$//'`
	[ -z "$value" ] && return 1
	value=`decode_type1 "$value"`
	[ $? != 0 ] && value=`decode_type2 "$value"`
	echo -n $value | sed 's/[:@]/ /g' | awk "{print \$$2}"
}

ip_get(){ 
	local value
	value=`value_get "$1" 3`
	[ -z "$value" ] && return 1
	echo "-s $value"
}
port_get(){
	local value
	value=`value_get "$1" 4`
	[ -z "$value" ] && return 1
	echo "-p $value"
}
passwd_get(){
	local value
	value=`value_get "$1" 2`
	[ -z "$value" ] && return 1
	echo "-k $value"
}
method_get(){
	local value
	value=`value_get "$1" 1`
	[ -z "$value" ] && return 1
	echo "-m $value"
}

#EXECUTE='ss-local -l "$LISTEN" $ip $port $passwd $method'
EXECUTE='ss-local -l $LISTEN $ip $port $passwd $method'
